// <auto-generated />
using System;
using EF_MSSQL_DataStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF_MSSQL_DataStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EasyMealCore.DomainModel.CartLine", b =>
                {
                    b.Property<int>("CartLineID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MealID");

                    b.Property<int?>("OrderID");

                    b.Property<int>("Quantity");

                    b.HasKey("CartLineID");

                    b.HasIndex("MealID");

                    b.HasIndex("OrderID");

                    b.ToTable("CartLine");
                });

            modelBuilder.Entity("EasyMealCore.DomainModel.InputMealsLine", b =>
                {
                    b.Property<int>("InputMealsLineID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MealID");

                    b.Property<int?>("MealWeekID");

                    b.Property<int>("Quantity");

                    b.HasKey("InputMealsLineID");

                    b.HasIndex("MealID");

                    b.HasIndex("MealWeekID");

                    b.ToTable("InputMealsLine");
                });

            modelBuilder.Entity("EasyMealCore.DomainModel.Meal", b =>
                {
                    b.Property<int>("MealID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<int>("Course");

                    b.Property<int>("Day");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<bool>("GlutenFree");

                    b.Property<string>("Image")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SaltFree");

                    b.Property<bool>("SugarFree");

                    b.HasKey("MealID");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("EasyMealCore.DomainModel.MealWeek", b =>
                {
                    b.Property<int>("MealWeekID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Shipped");

                    b.Property<int>("WeekNumber");

                    b.HasKey("MealWeekID");

                    b.ToTable("MealWeeks");
                });

            modelBuilder.Entity("EasyMealCore.DomainModel.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<bool>("GiftWrap");

                    b.Property<string>("Line1")
                        .IsRequired();

                    b.Property<string>("Line2");

                    b.Property<string>("Line3");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Shipped");

                    b.Property<string>("State")
                        .IsRequired();

                    b.Property<string>("UserName");

                    b.Property<int>("WeekNumber");

                    b.Property<string>("Zip");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EasyMealCore.DomainModel.CartLine", b =>
                {
                    b.HasOne("EasyMealCore.DomainModel.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealID");

                    b.HasOne("EasyMealCore.DomainModel.Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderID");
                });

            modelBuilder.Entity("EasyMealCore.DomainModel.InputMealsLine", b =>
                {
                    b.HasOne("EasyMealCore.DomainModel.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealID");

                    b.HasOne("EasyMealCore.DomainModel.MealWeek")
                        .WithMany("Lines")
                        .HasForeignKey("MealWeekID");
                });
#pragma warning restore 612, 618
        }
    }
}
